# Generated by Django 3.2.5 on 2021-08-03 19:14

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='content',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
