# Generated by Django 3.2.5 on 2021-08-03 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_video_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='content',
            new_name='url',
        ),
    ]
