# Generated by Django 3.2.5 on 2021-08-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='content',
        ),
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.ImageField(default=0, upload_to='images'),
            preserve_default=False,
        ),
    ]
